apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seafile.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.strategyUpdate }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "seafile.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "seafile.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if eq (include "configSecretsUsage" .) "true" }}
        checksum/config: {{ include (print $.Template.BasePath "/secret-configs.yaml") . | sha256sum | trunc 10 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "seafile.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.liveProbe }}
          livenessProbe:
            {{- toYaml .| nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml .| nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: seafile-main
              mountPath: /shared
              subPath: {{ .Values.persistence.subPath | default "data" }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if eq (include "configSecretsUsage" .) "true" }}
            {{- range $fileName, $file := .Values.configSecrets.files }}
            {{- if $file.content }}
            - name: config-files
              mountPath: "/shared/seafile/conf/{{ $fileName }}"
              subPath: {{ $fileName }}
            {{- end }}
            {{- end }}
            {{- end }}

      
      volumes:
        - name: seafile-main
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}data-{{ template "seafile.fullname" . }}{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if eq (include "configSecretsUsage" .) "true" }}
        - name: config-files
          secret:
            secretName: {{ include "seafile.fullname" . }}-config-files
            defaultMode: 0744
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
