{{- if eq (include "configSecretsUsage" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seafile.fullname" . }}-config-files
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
    {{- with .Values.configSecrets.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.configSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $fileName, $file := .Values.configSecrets.files }}
  {{- if $file.content }}
  {{ $fileName }}: {{ tpl $file.content $ | b64enc | quote }}
  {{- end }}
  {{- end }}
type: Opaque
{{- end }}